-- =============================================================================
-- Alinha questions.id ao short_id numérico (questões do GRUPO @g.us)
--
-- Atualiza também answers.question_id e published_question_id nos cadernos.
-- FKs são removidas e recriadas nesta transação (evita erro 23503).
--
-- Rode com o bot parado por alguns segundos.
-- =============================================================================

BEGIN;

ALTER TABLE public.questions ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Remove FKs que apontam para questions.id
ALTER TABLE public.answers
  DROP CONSTRAINT IF EXISTS answers_question_id_fkey;

ALTER TABLE public.caderno_questions
  DROP CONSTRAINT IF EXISTS caderno_questions_published_question_id_fkey;

ALTER TABLE public.caderno_private_send
  DROP CONSTRAINT IF EXISTS caderno_private_send_published_question_id_fkey;

DO $$
DECLARE
  temp_offset bigint := 50000000;
BEGIN
  CREATE TEMP TABLE question_id_remap ON COMMIT DROP AS
  SELECT
    q.id AS old_id,
    (q.short_id)::bigint AS new_id
  FROM public.questions q
  WHERE q.target_group_jid LIKE '%@g.us'
    AND q.short_id ~ '^\d+$';

  IF NOT EXISTS (SELECT 1 FROM question_id_remap) THEN
    RAISE NOTICE 'Nenhuma questao de grupo com short_id numerico para remapear.';
    RETURN;
  END IF;

  -- Fase 1: offset temporário (filhos primeiro; sem FK não há bloqueio)
  UPDATE public.answers a
  SET question_id = a.question_id + temp_offset
  FROM question_id_remap r
  WHERE a.question_id = r.old_id;

  UPDATE public.caderno_questions cq
  SET published_question_id = cq.published_question_id + temp_offset
  FROM question_id_remap r
  WHERE cq.published_question_id = r.old_id;

  UPDATE public.caderno_private_send cps
  SET published_question_id = cps.published_question_id + temp_offset
  FROM question_id_remap r
  WHERE cps.published_question_id = r.old_id;

  UPDATE public.questions q
  SET id = r.old_id + temp_offset
  FROM question_id_remap r
  WHERE q.id = r.old_id;

  -- Fase 2: id final = short_id
  UPDATE public.answers a
  SET question_id = r.new_id
  FROM question_id_remap r
  WHERE a.question_id = r.old_id + temp_offset;

  UPDATE public.caderno_questions cq
  SET published_question_id = r.new_id
  FROM question_id_remap r
  WHERE cq.published_question_id = r.old_id + temp_offset;

  UPDATE public.caderno_private_send cps
  SET published_question_id = r.new_id
  FROM question_id_remap r
  WHERE cps.published_question_id = r.old_id + temp_offset;

  UPDATE public.questions q
  SET id = r.new_id
  FROM question_id_remap r
  WHERE q.id = r.old_id + temp_offset;

  RAISE NOTICE 'Remapeadas % questao(oes) de grupo (id = short_id).', (SELECT COUNT(*) FROM question_id_remap);
END $$;

-- Espelha short_id nas respostas (caso ainda estejam com numero antigo)
UPDATE public.answers a
SET question_short_id = upper(q.short_id)
FROM public.questions q
WHERE a.question_id = q.id
  AND q.short_id IS NOT NULL
  AND upper(a.question_short_id) IS DISTINCT FROM upper(q.short_id);

ALTER TABLE public.answers
  ADD CONSTRAINT answers_question_id_fkey
  FOREIGN KEY (question_id) REFERENCES public.questions (id) ON DELETE CASCADE;

ALTER TABLE public.caderno_questions
  ADD CONSTRAINT caderno_questions_published_question_id_fkey
  FOREIGN KEY (published_question_id) REFERENCES public.questions (id) ON DELETE SET NULL;

ALTER TABLE public.caderno_private_send
  ADD CONSTRAINT caderno_private_send_published_question_id_fkey
  FOREIGN KEY (published_question_id) REFERENCES public.questions (id) ON DELETE SET NULL;

SELECT setval(
  pg_get_serial_sequence('public.questions', 'id'),
  COALESCE((SELECT MAX(id) FROM public.questions), 1),
  true
);

ALTER TABLE public.questions ALTER COLUMN id SET GENERATED ALWAYS;

COMMIT;

-- Conferência
SELECT id, short_id, creator_jid
FROM public.questions
WHERE target_group_jid LIKE '%@g.us'
  AND short_id ~ '^\d+$'
ORDER BY id;
